# Generated by Django 4.1.7 on 2023-02-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='brach',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
