# Generated by Django 4.1.7 on 2023-02-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_student_brach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='brach',
            new_name='branch',
        ),
    ]
